name: Deploy to GitHub Pages

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Github Actions playground
        runs-on: ubuntu-latest
        steps:
            - name: Show GitHub context
              env:
                 GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"

